FROM golang:onbuild


ENV BOOKREST_PORT 8000
ENV BOOKREST_DATABASE bookrest
ENV BOOKREST_DB_PORT 27017
ENV BOOKREST_DB_HOST recursing_haslett
ENV BOOKREST_DB_USERNAME ""
ENV BOOKREST_DB_PASSWORD ""


# ENV BOOKREST_CONNECTION_STRING = 

EXPOSE 8000
